server:
  port: 8761

spring:
  application:
    name: ead-service-registry

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

#spring:
#  profiles:
#    active: dev
#  application:
#    name: ead-service-registry