server:
  port: 8080

spring:
  application:
    name: ead-api-gateway
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      discovery:
        serviceId: ead-config-server
    gateway:
      routes:
        - id: authuser-service
#          uri: http://localhost:8087/
          uri: lb://EAD-AUTHUSER-SERVICE
          predicates:
            - Path=/ead-authuser/**
        - id: course-service
#          uri: http://localhost:8082/
          uri: lb://EAD-COURSE-SERVICE
          predicates:
            - Path=/ead-course/**
        - id: notification-service
          uri: lb://EAD-NOTIFICATION-SERVICE
          predicates:
            - Path=/ead-notification/**
eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
