#server:
#  port: 8082
#  servlet:
#    context-path: '/ead-course/'

spring:
  application:
    name: ead-course-service
  config:
    #    import: 'configserver:'
    import: 'optional:configserver:'
  cloud:
    config:
      discovery:
        serviceId: ead-config-server
#  datasource:
#    url: jdbc:postgresql://localhost:5432/ead-course
#    username: postgres
#    password: postgres
#  jpa:
#    hibernate:
#      ddl-auto: update
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      jdbc:
#        lob.non-contextual-creation: true
#    properties:
#      hibernate:
#        show_sql: true
#  output:
#    ansi:
#      enabled: Always
#  rabbitmq:
#    addresses: amqps://blsrpdgi:IC0YfHfXYJizl5SJO_21nDol7faxhdFH@fish.rmq.cloudamqp.com/blsrpdgi
#
#logging:
#  level:
#    com.ead: TRACE
#    root: INFO
#    org.springframework.web: DEBUG
#    org.hibernate: INFO
#    com.netflix.discovery: WARN
#
#ead:
#  api:
#    url:
#      user: 'http://ead-authuser-service/ead-authuser'
#  broker:
#    exchange:
#      userEventExchange: ead.userevent
#    queue:
#      userEventQueue:
#        name: ead.userevent.ms.course
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: 'http://localhost:8761/eureka'
#  instance:
#    hostname: localhost
#
#resilience4j:
#  retry:
#    instances:
#      retryInstance:
#        maxRetryAttempts: 3
#        waitDuration: 5s
