server:
  port: 8888

spring:
  application:
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/izaiasdb/jav-cou-decode01-repo
          default-label: main
          username: izaiasdb
          password: ***********************

ead:
  configServer:
    username: admin
    password: 'admin'
  serviceRegistry:
    username: admin
    password: 'admin'

eureka:
  client:
    serviceUrl:
#      defaultZone: 'http://localhost:8761/eureka'
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost

#spring:
#  profiles:
#    active: dev
#  application:
#    name: ead-config-server